// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8xZI2qI6t-gvHRKmiszBMM04TznRP-FU',
    appId: '1:356390346265:web:aa1f9b812512b442cbd488',
    messagingSenderId: '356390346265',
    projectId: 'fort-al-kalim',
    authDomain: 'fort-al-kalim.firebaseapp.com',
    databaseURL: 'https://fort-al-kalim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fort-al-kalim.firebasestorage.app',
    measurementId: 'G-4JSLTS7QKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2E53y2GgOVgegmnXKdVzuEZXxO8uYwIg',
    appId: '1:356390346265:android:dd025cb4496ccceacbd488',
    messagingSenderId: '356390346265',
    projectId: 'fort-al-kalim',
    databaseURL: 'https://fort-al-kalim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fort-al-kalim.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8xZI2qI6t-gvHRKmiszBMM04TznRP-FU',
    appId: '1:356390346265:web:bf7548ecfa59e5becbd488',
    messagingSenderId: '356390346265',
    projectId: 'fort-al-kalim',
    authDomain: 'fort-al-kalim.firebaseapp.com',
    databaseURL: 'https://fort-al-kalim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fort-al-kalim.firebasestorage.app',
    measurementId: 'G-H3BBTX3G1K',
  );
}
