// THIS FILE IS A PLACEHOLDER.
// Replace this with the actual firebase_options.dart generated by:
//   flutterfire configure
// after setting up your Firebase project at https://console.firebase.google.com

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported yet.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Only Android is supported currently.');
    }
  }

  // ⚠️  REPLACE with your real values from Firebase Console
  //     Project Settings → General → Your apps → google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'YOUR_API_KEY',
    appId:             'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId:         'YOUR_PROJECT_ID',
    storageBucket:     'YOUR_PROJECT_ID.appspot.com',
  );
}
