import 'dart:math';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

final friendRoomServiceProvider = Provider((ref) => FriendRoomService());

class FriendRoomService {
  final _db = FirebaseDatabase.instance;

  /// Generates a 6-character room code.
  String _generateRoomCode() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    final rnd = Random();
    return String.fromCharCodes(Iterable.generate(
      6,
      (_) => chars.codeUnitAt(rnd.nextInt(chars.length)),
    ));
  }

  /// Host creates a room. Returns the Room Code.
  Future<String> createRoom(String hostUid, String hostName, int hostLevel) async {
    final code = _generateRoomCode();
    await _db.ref('rooms/$code').set({
      'hostUid': hostUid,
      'hostName': hostName,
      'hostLevel': hostLevel,
      'status': 'waiting_for_guest', // waiting_for_guest, ready, playing
      'createdAt': ServerValue.timestamp,
    });
    return code;
  }

  /// Guest joins a room.
  Future<bool> joinRoom(String code, String guestUid, String guestName, int guestLevel) async {
    final roomRef = _db.ref('rooms/${code.toUpperCase()}');
    
    final result = await roomRef.runTransaction((obj) {
      if (obj == null) return Transaction.abort(); // Room doesn't exist
      
      final data = Map<String, dynamic>.from(obj as Map);
      if (data['status'] != 'waiting_for_guest') {
        return Transaction.abort(); // Full or already started
      }

      data['guestUid'] = guestUid;
      data['guestName'] = guestName;
      data['guestLevel'] = guestLevel;
      data['status'] = 'ready'; // Both are here
      return Transaction.success(data);
    });

    return result.committed;
  }

  /// Either player clicks "Ready to Play"
  /// Once both hit ready (if we required that), we'd launch game. 
  /// For now, host can just start it once someone joins.
  Future<String?> startGame(String code) async {
    final roomRef = _db.ref('rooms/${code.toUpperCase()}');
    final snapshot = await roomRef.get();
    
    if (!snapshot.exists) return null;
    final data = Map<String, dynamic>.from(snapshot.value as Map);
    
    if (data['status'] == 'playing') {
      // Game already generated by the other person
      return data['gameId'] as String;
    }

    final gameId = const Uuid().v4();
    final hostUid = data['hostUid'];
    final guestUid = data['guestUid'];

    // Create the game node
    await _db.ref('games/$gameId').set({
      'player1': hostUid,
      'player2': guestUid,
      'status': 'reading_phase',
      'isFriendMatch': true,
      'createdAt': ServerValue.timestamp,
    });

    // Update room status
    await roomRef.update({
      'status': 'playing',
      'gameId': gameId,
    });

    return gameId;
  }

  /// Stream to listen for room updates (e.g. someone joined)
  Stream<DatabaseEvent> watchRoom(String code) {
    return _db.ref('rooms/${code.toUpperCase()}').onValue;
  }

  /// Leave or destroy room
  Future<void> leaveRoom(String code) async {
    await _db.ref('rooms/${code.toUpperCase()}').remove();
  }
}
